[package]
name = "sudoku-solver"
version = "0.1.0"
edition = "2024"

[features]
default = ["solve_basic"]
solve_basic = []
solve_bit_masking_v1 = []
solve_bit_masking_v2 = []
solve_bitset_masking_v1 = []
measure_runtime = []

[dev-dependencies]
criterion = "0.7.0"

[dependencies]

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
codegen-units = 1
debug = "none"
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 3
overflow-checks = false
panic = "abort"
rpath = false
split-debuginfo = "off"
strip = "symbols"