[package]
name = "sudoku-solver"
version = "0.1.0"
edition = "2024"

[features]
default = ["solve_basic"]
solve_basic = []
solve_grid_bit_masking = []
solve_grid_bit_masking_bitset = []
measure_runtime = []

[dev-dependencies]
criterion = "0.7.0"

[dependencies]

[[bench]]
name = "benchmarks"
harness = false